services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env

volumes:
  mongodb_data: 